### ISSUE TITLE
editor3d does not statt

### ISSUE THREAD

**Issue by zevix** [kpiorno/kivy3dgui#10]
Note: all other demos run properly

[INFO   ] [CutBuffer   ] cut buffer support enabled
 Traceback (most recent call last):
   File "editor3d.py", line 445, in <module>
     Minimal3dApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 829, in run
     root = self.build()
   File "editor3d.py", line 238, in build
     self.space_editor = SpaceEditor(layout3d, self, self.editor_manager)
   File "/tmp/kivy3dgui/editor/space_editor.py", line 37, in __init__
     node = Builder.load_string(dedent(axis.format(e, colors[i])))
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 405, in load_string
     rule_children=rule_children)
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 707, in _apply_rule
     e), cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 9:
 ...
       7:    always_on_top: True
       8:    receive_shadows: False
 >>    9:    meshes: ("./editor/meshes/x-rot-axis.obj",)
      10:    Button:
      11:        id: c_button
 ...
 AttributeError: 'NoneType' object has no attribute 'add_node'
   File "/usr/lib/python2.7/dist-packages/kivy/lang/builder.py", line 700, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 497, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 839, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 544, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 599, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/tmp/kivy3dgui/kivy3dgui/node.py", line 303, in on_meshes
     self.parent.add_node(self)

**Comment by kpiorno** [comment]
Which Kivy version are you using?

**Comment by stengergilles** [comment]
Hello,
Same issue here. 
Trying with PyDroid3 on android ( Kivy 1.11.1 /Python 3.8 )
Regards. 
Gilles

**Comment by kpiorno** [comment]
Ok, I'll check on that ASAP.

**Comment by kpiorno** [comment]
> Hello,
> Same issue here.
> Trying with PyDroid3 on android ( Kivy 1.11.1 /Python 3.8 )
> Regards.
> Gilles

Hi Giller, did you test another example using these specs on Android?

**Comment by stengergilles** [comment]
Hello
Sorry for the late reply I'm on holiday.:-)
checkers.py give me the same error
example.py/example2.py/tour3d exit with no logs (last message is "Starting application main loop")

**Comment by kpiorno** [comment]
Don't worry Gilles :).I will take a look at that.

**Comment by kmcasi** [comment]
Same error on editor3d and checkers like on the opened issue.

**Kivy:** 2.2.0.dev0
**Python:** 3.11.0
**OS:** Windows 10 Pro N, 21H2

I installed Kivy by github link, was the only option what worked on my laptop.
