### ISSUE TITLE
init takes no parameters

### ISSUE THREAD

**Issue by HarryFengYX** [kpiorno/kivy3dgui#8]
Traceback (most recent call last):
   File "C:\Users\Harry\Desktop\mykivy\kivy3dgui-master\example.py", line 197, in <module>
     ExampleApp().run()
   File "C:\Users\Harry\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "C:\Users\Harry\Desktop\mykivy\kivy3dgui-master\example.py", line 191, in build
     ''')
   File "C:\Users\Harry\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\lang\builder.py", line 381, in load_string
     widget = Factory.get(parser.root.name)()
   File "C:\Users\Harry\Desktop\mykivy\kivy3dgui-master\kivy3dgui\layout3d.py", line 159, in __init__
     self.create_canvas()
   File "C:\Users\Harry\Desktop\mykivy\kivy3dgui-master\kivy3dgui\layout3d.py", line 218, in create_canvas
     canvas_size=self.canvas_size, id="CANVAS3D")
   File "C:\Users\Harry\Desktop\mykivy\kivy3dgui-master\kivy3dgui\canvas3d.py", line 226, in __init__
     super(Canvas3D, self).__init__(**kwargs)
   File "C:\Users\Harry\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Users\Harry\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Users\Harry\AppData\Local\Programs\Python\Python36-32\lib\site-packages\kivy\uix\widget.py", line 337, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:5332)
 TypeError: object.__init__() takes no parameters

**Comment by kpiorno** [comment]
Please can you specify the kivy version?

**Comment by mfkenson** [comment]
would happen under python3

**Comment by kpiorno** [comment]
Python3 and Kivy 1.10 though. I'm working on the issue right now.

**Comment by kpiorno** [comment]
Please do some tests. Thanks
